---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

platform:
  os: linux
  arch: amd64
  
#clone:
#  depth: 50

server:
  #image: ubuntu-20-04-x64
  image: ubuntu-18-04-x64
  #image: debian-10-x64
  #image: centos-7-x64
  #image: fedora-33-x64
  #size: s-1vcpu-1gb
  #size: s-1vcpu-2gb
  size: s-2vcpu-2gb
  #size: s-2vcpu-4gb
  region: sfo3

steps:
- name: build
  commands:
  - apt-get update -y -qq 
  - apt-get upgrade -y
  - apt install -y python3 python3-pip python3-venv
  - apt-get install -y ansible
  - ansible-playbook install.yml

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
