---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

platform:
  os: linux
  arch: amd64
  
server:
  #image: ubuntu-20-04-x64
  image: ubuntu-18-04-x64
  #image: debian-10-x64
  #image: centos-7-x64
  #image: fedora-33-x64
  #size: s-1vcpu-1gb
  #size: s-1vcpu-2gb
  size: s-2vcpu-2gb
  #size: s-2vcpu-4gb
  region: sfo3

steps:
- name: build
  commands:
  #- apt-mark hold linux-image-generic linux-headers-generic
  - apt-get -qq update -y
  - apt-get -qq upgrade -y
  - apt-get -qq install -y ansible python3 python3-pip python3-venv
  - ansible-playbook install.yml

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
