---
language: python
sudo: required

jobs:
  include:
    # https://docs.travis-ci.com/user/reference/overview/#linux
    - name: Linux install test
      os: linux
      dist: focal
      virt: lxd
      before_install:
        - sudo apt-get update -qq

    # https://docs.travis-ci.com/user/reference/osx/
    - name: macOS install test
      os: osx
      osx_image: xcode12.2
      language: shell

#branches:
#  only:
#    - master

install:
  - pip3 install ansible

notifications:
  email:
    on_failure: always
    on_success: never

script:
  #- ansible-playbook install.yml --syntax-check
  - travis_wait 30 ansible-playbook install.yml
  - go version
  - source ~/.bashrc
  - alias weather >/dev/null 2>&1 && echo "weather alias found" || echo "weather is not an alias" && exit 1
