---
language: python
sudo: required

jobs:
  include:
    # https://docs.travis-ci.com/user/reference/overview/#linux
    - name: Linux Test
      os: linux
      dist: focal
      virt: vm
      before_install:
        - sudo apt-get update -qq

    # https://docs.travis-ci.com/user/reference/osx/
    - name: macOS Test
      os: osx
      osx_image: xcode12.2
      language: shell

#branches:
#  only:
#    - master

install:
  - pip3 install ansible

notifications:
  email:
    on_failure: always
    on_success: never

script:
#  - ansible-playbook install.yml --syntax-check
  - "cd chadmayfield/dotfiles && ansible-playbook install.yml"
