---
dist: xenial
env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH
                
language: python

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - pip3 install ansible

script:
#  - ansible-playbook install.yml --syntax-check
  - ansible-playbook install.yml --connection=local --sudo
