---
language: python
sudo: required

jobs:
  include:
    # https://docs.travis-ci.com/user/reference/overview/#linux
    - name: Linux install test
      os: linux
      dist: focal
      virt: vm

    # https://docs.travis-ci.com/user/reference/osx/
    - name: macOS install test
      os: osx
      osx_image: xcode12.2
      language: shell
      addons:
        homebrew:
        brewfile: Brewfile
        update: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi

#branches:
#  only:
#    - master

install:
  - pip3 install ansible

notifications:
  email:
    on_failure: always
    on_success: never

script:
  #- ansible-playbook install.yml --syntax-check
  - ansible-playbook install.yml
  - go version
  - source ~/.bashrc
  #- alias weather >/dev/null 2>&1 && exit 0 || echo "alias not found" && exit 1
