---
language: python
python: "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
#  - ansible-playbook install.yml --syntax-check
  - ansible-playbook install.yml --connection=local --sudo
